.\"	$OpenBSD$
.\"
.\" Copyright (c) 2019 Martijn van Duren <martijn@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt FILTER-DNSBL 8
.Os
.Sh NAME
.Nm filter-dnsbl
.Nd block senders based on dnsbl
.Sh SYNOPSIS
.Nm
.Op Fl amv
.Ar blacklist
.Ar ...
.Sh DESCRIPTION
.Nm
looks up the IP address of the sender at the
.Ar blacklist
.Pq a domain name
and by default drops the connection if it is found.
If the
.Fl m
flag is specified it will allow the message to continue, but it will be marked
with an X-Spam and X-Spam-DNSBL header.
For more verbose logging the
.Fl v
flag can be used.
If the
.Fl p
flag is specified, the message will be permanently rejected with a 550 error
code.
.Pp
If you use paid blacklists, you might want to avoid your key being leaked in
the response to foreign MTAs. You can prepend the character 
.Ic  : 
to the name of the list to avoid the first part (key) to be leaked.
For example
.Ic :abcde1234567890.myblacklist.tld
will become
.Ic myblacklist.tld
in the MTA response. Note that the verbose log will still show the original
list.
.Sh SEE ALSO
.Xr smtpd 8
